//Category
export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

//User
export const LOGGED_USER = "LOGGED_USER"
export const LOGGED_USER_CLEAR = "LOGGED_USER_CLEAR"
export const CURRENT_USER = "CURRENT_USER"
export const USER_UPDATE_RES = "USER_UPDATE_RES"
export const USER_UPDATE_RES_CLEAR = "USER_UPDATE_RES_CLEAR"
export const GET_USER_CHANNELS = "GET_USER_CHANNELS"
export const GET_SUBSCRIPTIONS = "GET_SUBSCRIPTIONS"
export const GET_SHARED_PHOTOS = "GET_SHARED_PHOTOS"
export const GET_LIKED_PHOTOS = "GET_LIKED_PHOTOS"

//Channel
export const CHANNEL_CREATE_RESPONSE = "CHANNEL_CREATE_RESPONSE"
export const CHANNEL_UPDATE_RESPONSE = "CHANNEL_UPDATE_RESPONSE"
export const GET_CHANNEL_PHOTOS = "GET_CHANNEL_PHOTOS"
export const GET_CHANNEL_SUBSCRIBERS = "GET_CHANNEL_SUBSCRIBERS"
export const GET_CHANNEL_DETAIL = "GET_CHANNEL_DETAIL"
export const GET_CHANNEL_OWNER = "GET_CHANNEL_OWNER"
export const GET_CHANNEL_ADMINS = "GET_CHANNEL_ADMINS"
export const GET_PHOTO_GALERY = "GET_PHOTO_GALERY"
export const GET_CHANNEL_CATEGORIES = "GET_CHANNEL_CATEGORIES"
export const ADD_CHANNEL_ADMIN = "ADD_CHANNEL_ADMINS"
export const REMOVE_CHANNEL_ADMIN = "REMOVE_CHANNEL_ADMIN"

//Photo
export const PHOTO_CREATE = "PHOTO_CREATE"