//Category
export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

//Auth
export const AUTH_LOGIN_RESPONSE = "AUTH_LOGIN_RESPONSE"
export const AUTH_REGISTER_RESPONSE = "AUTH_REGISTER_RESPONSE"
export const AUTH_LOGOUT_RESPONSE = "AUTH_LOGOUT_RESPONSE"
export const AUTH_STATE_CLEAR = "AUTH_STATE_CLEAR"

//User
export const LOGGED_USER = "LOGGED_USER"
export const LOGGED_USER_CLEAR = "LOGGED_USER_CLEAR"
export const CURRENT_USER = "CURRENT_USER"

//Channel
export const CHANNEL_CREATE = "CHANNEL_CREATE"
export const GET_CHANNEL_PHOTOS = "GET_CHANNEL_PHOTOS"
export const GET_CHANNEL_SUBSCRIBERS = "GET_CHANNEL_SUBSCRIBERS"
export const GET_CHANNEL = "GET_CHANNEL"

//Photo
export const PHOTO_CREATE = "PHOTO_CREATE"